### ISSUE TITLE
KADENCE + CODE SNIPPETS + CLOUDWAYS + CLOUDFLARE + WP-ROCKET

### ISSUE THREAD

**Issue by mywebguytaylor** [lukecav/awesome-wp-speed-up#10]
I am trying to get my Kadence site to pass 90 Page Speed score, and have a few questions. I have a few questions:

1. What are the pros and cons of using CODE SNIPPETS Plugin instead of GTM ? It seems like managing everything would be much easier with CODE SNIPPETS, because I am able to see them inside of my WP admin, however, I am unclear on what the point is for having GTM (Google Tag Manager)? I must be missing something? Most of my sites are smaller sites, and not large corporation sites, so I don't have any problem of getting access to FTP to change scripts, etc, is that the biggest pro for GTM? I want to keep my site as lightweight as possible. I use WP ROCKET, and also, they have ADD ON options which load FB PIXEL and GA locally, and their support staff says it doesn't work with GTM : /

2. How do I add the GA code properly to CODE SNIPPETS? Does it have to be in the head and the body?

3. How do I add the GTM code properly to CODE SNIPPETS, if I decide to use GTM as well?

4. How do I add the Facebook Pixel to CODE SNIPPETS? Should I also install the FACEBOOK FOR WORDPRESS, by Facebook? which one should I use? What are the pros and cons of each ? https://wordpress.org/plugins/official-facebook-pixel/

5. WP ROCKET options has this section called ADD ONS, and I am unsure how this works. Does anyone have any advice ? https://www.mycart123.com/uploads/screenshot31057F93.png

6. WP ROCKET LAZY LOAD, what's the default best practice here, should I check this or no? I thought Wordpress 7.2 is lazy loading all images by default now? Even when I do check this option, I am still getting errors in page speed test saying I should lazy load images on my site, so I am unsure if that even works?

7. Kadence Theme has an option to LOAD GOOGLE FONTS LOCALLY, can anyone offer a simple explanation or some stepwise instructions on how to do that? I am using Digital Ocean Cloudways Hosting. I use CLOUDFLARE for caching.

8. Does anyone have smart suggestions for developing on a WP site and minimizing latency when updating a page?

9. What is the meaning of life? 😉

**Comment by lukecav** [comment]
The code snippets plugin will store the code in the database and then use it. The plugin works the same as adding code into the functions.php of the child theme.

https://wordpress.org/plugins/google-site-kit/
https://sitekit.withgoogle.com/documentation/

https://docs.wp-rocket.me/category/1140-wp-rocket-add-ons

https://wordpress.org/plugins/host-analyticsjs-local/
https://wordpress.org/plugins/host-webfonts-local/

**NOTE: WordPress introduced LazyLoad into core from version 5.5. This will be automatically disabled when WP Rocket's LazyLoad is active.**
https://docs.wp-rocket.me/article/1141-using-lazyload-in-wp-rocket
https://make.wordpress.org/core/2020/01/29/lazy-loading-images-in-wordpress-core/

I would check the KB https://kadence-theme.com/knowledge-base/ for more info on the Kadence theme locally loading Google web fonts.

If using the Kadence theme then you can already easily add any scripts into the header of the site for example Google Tag Manager.
https://kadence-theme.com/knowledge-base/pro-addon/how-to-add-scripts-in-header-footer/
https://developers.google.com/tag-manager/quickstart
