### ISSUE TITLE
Torque in wrong category

### ISSUE THREAD

**Issue by hexydec** [lukecav/awesome-wp-speed-up#11]
Hi, thanks for listing my plugin Torque. But it is not a page caching plugin, it is more focused on minification and transport optimisation.

Could you move it into a more appropriate category?

**Comment by lukecav** [comment]
Yep I can move it.

**Comment by lukecav** [comment]
K done.
https://github.com/lukecav/awesome-wp-speed-up/commit/0b8c470f840182acd37dcb6e4edf4f21122d211f
