### ISSUE TITLE
HTTP/3

### ISSUE THREAD

**Issue by tomzur** [lukecav/awesome-wp-speed-up#18]
Hi Luke, your list is pretty extensive and not much to add, however, I noticed that HTTP/3 is not mentioned there. we have a detailed overview of it in case you would like add as a resource https://kinsta.com/blog/http3/
Thanks and Happy New Year!

**Comment by lukecav** [comment]
K added.
https://github.com/lukecav/awesome-wp-speed-up/commit/153c42d934bdf9b0ecf1f15b9761784fd92777b2
