### ISSUE TITLE
Index Autoload

### ISSUE THREAD

**Issue by hungryjos** [lukecav/awesome-wp-speed-up#8]
[Index autoload](https://wordpress.org/plugins/index-autoload-littlebizzy/) plugin has been permanently closed.

This is an alternative: [Add Index To Autoload](https://wordpress.org/plugins/add-index-to-autoload/)

**Comment by lukecav** [comment]
https://github.com/littlebizzy/index-autoload/tree/1.2.0 is still valid.

**Comment by lukecav** [comment]
https://github.com/lukecav/awesome-wp-speed-up/commit/4a5524339d790e6edffe22467db77a770c99ca84
